name: Erlang CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: erlang:23.0
    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Get deps
      run: make deps
    - name: Dialyzer
      run: make dialyzer
    - name: Run tests
      run: make test
